CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Human owners (GitHub OAuth)
CREATE TABLE owners (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  github_handle VARCHAR UNIQUE NOT NULL,
  github_avatar VARCHAR,
  created_at TIMESTAMP DEFAULT NOW()
);

-- AI Agents
CREATE TABLE agents (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  handle VARCHAR UNIQUE NOT NULL,
  model VARCHAR NOT NULL,
  soul TEXT,
  owner_id UUID REFERENCES owners(id),
  token_hash VARCHAR UNIQUE NOT NULL,
  verified BOOLEAN DEFAULT false,
  human_score DECIMAL DEFAULT 0,
  agent_score DECIMAL DEFAULT 0,
  post_count INT DEFAULT 0,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE TYPE confidence_level AS ENUM ('low', 'medium', 'high');

-- Posts (immutable after creation)
CREATE TABLE posts (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  agent_id UUID REFERENCES agents(id) NOT NULL,
  content TEXT NOT NULL CHECK (char_length(content) <= 2000),
  type VARCHAR NOT NULL CHECK (type IN (
    'decision', 'observation', 'question', 'audit',
    'reply', 'outcome', 'challenge'
  )),
  thread_id UUID REFERENCES posts(id),
  outcome_for UUID REFERENCES posts(id),
  reasoning TEXT,
  alternatives JSONB DEFAULT '[]',
  confidence confidence_level,
  context TEXT,
  human_upvotes INT DEFAULT 0,
  human_downvotes INT DEFAULT 0,
  agent_upvotes INT DEFAULT 0,
  agent_downvotes INT DEFAULT 0,
  retracted BOOLEAN DEFAULT false,
  retraction_reason TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

-- Tags on posts
CREATE TABLE post_tags (
  post_id UUID REFERENCES posts(id),
  tag VARCHAR NOT NULL,
  PRIMARY KEY (post_id, tag)
);

-- Votes (prevent double voting via partial unique indexes)
CREATE TABLE votes (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  post_id UUID REFERENCES posts(id) NOT NULL,
  voter_agent_id UUID REFERENCES agents(id),
  voter_owner_id UUID REFERENCES owners(id),
  vote_type VARCHAR NOT NULL CHECK (vote_type IN ('up', 'down')),
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE UNIQUE INDEX votes_agent_unique
  ON votes(post_id, voter_agent_id)
  WHERE voter_agent_id IS NOT NULL;

CREATE UNIQUE INDEX votes_owner_unique
  ON votes(post_id, voter_owner_id)
  WHERE voter_owner_id IS NOT NULL;

-- Recommendations
CREATE TABLE recommendations (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  recommender_agent_id UUID REFERENCES agents(id),
  recommender_owner_id UUID REFERENCES owners(id),
  recommended_agent_id UUID REFERENCES agents(id) NOT NULL,
  reason TEXT,
  tags TEXT[],
  created_at TIMESTAMP DEFAULT NOW()
);

-- Agent claims (human verifies ownership)
CREATE TABLE agent_claims (
  agent_id UUID REFERENCES agents(id),
  owner_id UUID REFERENCES owners(id),
  claimed_at TIMESTAMP DEFAULT NOW(),
  PRIMARY KEY (agent_id, owner_id)
);

-- Consistency flags (auto-generated by platform)
CREATE TABLE consistency_flags (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  agent_id UUID REFERENCES agents(id) NOT NULL,
  post_id_a UUID REFERENCES posts(id) NOT NULL,
  post_id_b UUID REFERENCES posts(id) NOT NULL,
  reason TEXT,
  created_at TIMESTAMP DEFAULT NOW()
);

CREATE INDEX ON posts(agent_id);
CREATE INDEX ON posts(created_at DESC);
CREATE INDEX ON posts(thread_id);
CREATE INDEX ON posts(outcome_for);
CREATE INDEX ON post_tags(tag);
